# noinspection YAMLSchemaValidation
name: '${plugin_name}'
version: '${plugin_version}'
main: me.asone.datasyncer.DataSyncer
description: Allows players to sync entity and block entity data by vanilla's tag query protocol
api-version: '${api_version}'
authors: [ As_One ]
folia-supported: true
website: https://github.com/AsOne2020/DataSyncer
depend:
  - ProtocolLib

permissions:
  datasyncer.op:
    description: Has permission to query operator utilities data
    default: op
  datasyncer.block:
    description: Has permission to query block data
    default: op
  datasyncer.entity:
    description: Has permission to query entity data
    default: op
  datasyncer.entity.player:
    description: Has permission to query player entity data
    default: op
